GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/3

###
GET http://localhost:3001/api/unknown/endpoint

###
GET http://localhost:3001/api/persons/65477fb6e8906a23099ee60d

###
DELETE http://localhost:3001/api/persons/65477cadd27f9c98dd5e899e

###
PUT http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Poppinp Lovenadadss",
    "number": "51-00124-320"
}

###
PUT http://localhost:3001/api/persons/6547d26480918f4fa510fa9c
Content-Type: application/json

{
    "name": "dex",
    "number": "51-00124-330",
    "id": "6547d26480918f4fa510fa9c"
}