GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/3

###
GET http://localhost:3001/api/persons/65477cadd27f9c98dd5e899e

###
DELETE http://localhost:3001/api/persons/65477cadd27f9c98dd5e899e

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "dss",
    "number": "213123"
}